services:
  db:
    build: .
    image: my-image-mysql:latest
    container_name: my-container-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3307:3306
    volumes:
      - my-volume-mysql-phpmyadmin:/var/lib/mysql
    networks:
      - my-network-mysql-phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: my-container-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - my-network-mysql-phpmyadmin

volumes:
  my-volume-mysql-phpmyadmin:
    external: true

networks:
  my-network-mysql-phpmyadmin:
    external: true
